/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DesignPatternMultiThread;

import DesignPatternMultiThread.chap8.Chap8;

public class App {
    public static void main(String[] args) {
//        var intro = new Intro();
//        intro.main();

//        Chap1.main();
//        Chap2.main();
//        Chap3.main();
//        Chap4.main();
//        Chap5.main();
//        Chap6.main();
//        Chap7.main();
        Chap8.main();
    }
}
